### PR TITLE
Add Malay translation

### PR DESCRIPTION
**Pull request by inche-ali**
Translation in Malay (Bahasa Melayu)
used the wrong branch "master" before.. #295
for issue #294

### CODE REVIEW

**Comment by juliannagler** [comment]
Hey @inche-ali, great work here! We've had a native speaker review the translations, and they've made a few comments. Below is a breakdown of the suggested changes, along with a full string dump with the changes included. 

[Requested Changes](https://github.com/facebook/fbctf/files/590377/Copy.of.FBCTF_Changes_Tracker_Malay.1.xlsx)

[Full String Dump](https://github.com/facebook/fbctf/files/590373/Malay.FBCTF.Translation.final.docx)

Once you make the suggested changes, we'll merge! Thanks again.

**Comment by inche-ali** [comment]
I have made the changes but there is a few suggested change I modified 
due to the meaning of **'base'** in malay it can be **'pengkalan'** or **'asas'** 
for this game context I chosed **'pengkalan'**

Also there is one word **'Dec'** comes from **'Decrement'** in malay it is **'Susutan'**
So I use **'Susut'** and **'Susutan'**
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Kitaran Asas  -> Kitaran Pangkalan
Dek Bonus Lalai -> Susutan Bonus Lalai
-Dek -> -Susut
Tahap Asas Baru -> Tahap Pangkalan Baru
Semua Tahap Asas -> Semua Tahap Pangkalan
Tahap Asas -> Tahap Pangkalan
Pengurusan Tahap -> Pengurusan Pangkalan
Tambahkan Tahap Asas -> Tambah Tahap Pangkalan
Asas -> Pangkalan
mata_asas_ -> mata_pangkalan_
mata_asas -> mata_pangkalan
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by juliannagler** [comment]
Thanks for making those changes, @inche-ali. We'll trust your judgment on "base" and "dec"! 

Merging now. As you use the translated version, please file issues for any formatting problems you run into. 

Thanks again for the great work here!

**Comment by inche-ali** [comment]
@juliannagler  ..the merged PR is not the correct one,sorry.
I forgot to commit after pull & stash..
I have created another PR  #363 to fix this.. Sorry for any inconvenience caused.

**Pull request merged**
