### PR TITLE
add user / pass for VM

### PR DESCRIPTION
**Pull request by mtmcgrew**
This adds the username and password for the vagrant VM to the docs

### CODE REVIEW

**Comment by gsingh93** [comment]
The username and password are in the paragraph below the one you modified. Do you think we should move it?

**Comment by mtmcgrew** [comment]
admin / password? That for the web ui, not the vm, right?

**Comment by gsingh93** [comment]
Yea, that's for the web UI, I didn't realize you were talking about the VM. Are you not using `vagrant` from the command line? `vagrant ssh` should log you in without the need for a password.

**Comment by mtmcgrew** [comment]
Ahhh ok, that makes sense. I'll change the wording to that. I don't think that's obvious to someone un-familiar with vagrant. Someone asked me today at a ctf how to log into the vm.

**Comment by gsingh93** [comment]
That's a good point, I'll add the note about `vagrant ssh` to the README. Are you fine with me closing this PR?

**Pull request closed without merging**
