### PR TITLE
Force Attachment Permissions

### PR DESCRIPTION
**Pull request by justinwray**
* Set uploaded attachment permissions to 0600.

### CODE REVIEW

**Comment by gsingh93** [comment]
Just to be super safe, can you assert that the result of the chmod is `true`?

**Comment by wrayjustin** [comment]
Updated with validation of the permission change.

**Comment by justinwray** [comment]
Updated with validation of the permissions.

**Comment by gsingh93** [comment]
`chmod` returns true or false depending on whether it succeeded or failed in changing the permissions. Is there any benefit to the assertion you added as opposed to just asserting the return value is `true`?

**Comment by justinwray** [comment]
The implicit permission check was added for extra insurance of the file permissions.  However, there doesn't seem to be much benefit as the chmod() function should always provide a factual return (that is, there are not any documented cases where the chmod return is inaccurate).

I've updated the code to verify the return.

**Pull request merged**
