### PR TITLE
Avoid multiple entry in /etc/apt/sources.list when re-install

### PR DESCRIPTION
**Pull request by inche-ali**
fix for issue #312

### CODE REVIEW

**Comment by gsingh93** [comment]
It looks like MyCLI now supports installing from pip. I think it would make more sense to install `pip` and then install `mycli` from there.

**Comment by javuto** [comment]
Agree with @gsingh93, better install pip, which should be just ```package python-pip```, then install it there.

**Comment by inche-ali** [comment]
modified the provision.sh & lib.sh files...now use pip to install mycli
done rebase to fbctf/master too..

**Comment by javuto** [comment]
Looks good to me, cleaner and no need to add a new repository. @gsingh93?

**Comment by gsingh93** [comment]
Merged, thanks!

**Pull request merged**
