### PR TITLE
Configuration option for arbitrary game duration added

### PR DESCRIPTION
**Pull request by markszabo**
As requested in #78 the possibility to select arbitrary game duration is implemented:
selection_001
TODO: if a duration longer than 99 hours is selected, then the Gameclock overlaps:
selection_002

### CODE REVIEW

**Comment by gsingh93** [comment]
Thanks for the PR! While we do want this feature, we probably need to figure out how to fix the overlap before we do this. We probably just need to space out the `:` a bit more.

**Comment by markszabo** [comment]
I fixed the overlap, now it looks like this:
Normal operation below 24 hours is not changed:
selection_004
Above 24 hours the milliseconds are gone, and we have days instead:
selection_003
selection_002
It also works above 99 days:
selection_001
What do you think?

**Comment by javuto** [comment]
Let's get this merged! Can you rebase with current master and update this? I can merge it right away. Thanks again for the PR @markszabo!

**Comment by markszabo** [comment]
I just did the rebase and resolved the conflicts. Sorry for the long reply, I was AFK.

**Comment by javuto** [comment]
Looks good, any concerns here @gsingh93?

**Comment by javuto** [comment]
On second thoughts, we need a way to make a game to last 1 day, 3 hours and 17 minutes. Probably we can integrate it here. Thoughts @markszabo?

**Comment by markszabo** [comment]
Well it's not too complicated to integrate, but do we really need this? I mean people will usually start games for 5 hour, for 2 days or for 30 days. And if they really want to start one for 1 day and 3 hours, they can still start it for 27 hours. But if you think it's really needed, I can do it.

**Comment by gsingh93** [comment]
@markszabo your PR is a bit messed up because it includes commits from other people. Can you remove the extra commits from the PR? Let me know if you need help.

I think we can leave off the minutes stuff for this PR. I can see it being useful if we for some reason want to change the end time while the game is running (i.e. we'd set a new end time that would be 1 hour and 13 minutes from now), but I don't think we support changing the end time anyway, so it's fine for now.

**Comment by markszabo** [comment]
I did the rebase again, and those commits disappeared. Is it okay now?

**Pull request merged**
