### PR TITLE
Merge Deconflict of /dev and /master

### PR DESCRIPTION
**Pull request by justinwray**
* This is a merge of the /dev and /master branch, including the new branding code and password complexity code, over top of the existing Live Sync API.

* This PR deconflicts the merge conflicts found between /dev and /master.

* Full commit logs for the /dev changes can be found in PR #448 and #442

### CODE REVIEW

**Comment by gsingh93** [comment]
Seems like some test issues, I can merge when fixed.

**Comment by justinwray** [comment]
Looking at the log, this seems to be the current grunt/lint/flow error (see #499 & #500), #502 is a temporary fix.

**Comment by PhilippBehmer** [comment]
#502 got merged and now the build is OK! \o/

**Comment by gsingh93** [comment]
Merged, thanks.

**Pull request merged**
