### PR TITLE
Add new translations for spanish

### PR DESCRIPTION
**Pull request by DaniLabs**
I add a new tags for translations and change some lines.

### CODE REVIEW

**Comment by DaniLabs** [comment]
I have just create a CLA signed

**Comment by DaniLabs** [comment]
Anyone know where is the error? :S

**Comment by justinwray** [comment]
`master` is currently failing to build due to a change with Travis-CI.

This has recently been resolved within `dev`.

As such there are a few options:

1. Close this PR and submit against `dev`, making sure you are committing against the latest `dev` head and are conflict-free.
1. Wait until the current work within `dev` is merged into `master`, and `dev` is in sync with `master`, then submit this PR against `dev`.
1. Wait until the current work within `dev` is merged into `master`, and rebase this PR.

We will be syncing the current work from `dev` into `master` soon.

**Comment by justinwray** [comment]
@DaniLabs 

Thank you again for your contribution to the project!  Please close this issue and resubmit your changes to the `dev` branch.  Make sure you use the latest copy of the `dev` branch and rebase your changes accordingly.

**Comment by DaniLabs** [comment]
Okay I closed the issue

**Comment by justinwray** [comment]
@DaniLabs You can resubmit the changes against the `dev` branch.  Just be sure to rebase and correct and conflicts.

**Pull request closed without merging**
