### PR TITLE
Added Ubuntu/trusty64 VM.box URL

### PR DESCRIPTION
**Pull request by AshutoshKumarAnand**

### CODE REVIEW

**Comment by gsingh93** [comment]
Thanks for the PR! I don't think this parameter is necessary, is there any reason you want to add it? If not, I'll be closing this PR.

**Comment by javuto** [comment]
Agree with @gsingh93, not sure what is the benefit of this.

**Comment by AshutoshKumarAnand** [comment]
The person who is first time installing on their Ubuntu machine were
getting errors.

Also directly adding Ubuntu trusty 64 is not working. So this would help
any user to directly install fbctf without any problem.

**Comment by gsingh93** [comment]
Can you elaborate on what the errors are and the exact steps you're doing? I bet there's a better fix.

**Pull request closed without merging**
