### PR TITLE
Changed 2 apt-get installs to package call.

### PR DESCRIPTION
**Pull request by ingoha**
Fixes install for me.

### CODE REVIEW

**Comment by ingoha** [comment]
Fixes provisioning:
git clone ... and vagrant up failed; hhvm was not installed

**Comment by facebook-github-bot-0** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by ingoha** [comment]
Added a hint to the README file for all non-english users.

**Comment by ingoha** [comment]
Just signed the CLA :-)

**Comment by facebook-github-bot-7** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by javuto** [comment]
Hey @ingoha , good job! Can you stash your commits? Then I am ready to merge this 👍

**Comment by ingoha** [comment]
Sorry if it is a noob question, but how do I do this?

**Comment by javuto** [comment]
There is a good guide on how to do this here: https://github.com/facebook/osquery/blob/master/CONTRIBUTING.md

**Comment by ingoha** [comment]
Cool :-) Thanks for the link - I think I made it. So you did mean "squash" the commits, not "stash" right? Did confuse me ;-)

**Comment by gsingh93** [comment]
Thanks!

**Pull request merged**
