### PR TITLE
farsi language is added.

### PR DESCRIPTION
**Pull request by mabdi**
language file for farsi.

### CODE REVIEW

**Comment by javuto** [comment]
Ping @mabdi, can you please sign the CLA? Thank you!

**Comment by juliannagler** [comment]
Great work here @mabdi ! We've had a local speaker review and validate the translation. 

The suggested changes can be found [here](https://github.com/facebook/fbctf/files/623240/Copy.of.FBCTF_Changes_Tracker_fa_IR.1.-2.xlsx)

The full string dump, including the suggested changes, can be found [here](https://github.com/facebook/fbctf/files/623242/FBCTF.Farsi.Translation.1.docx)

Once you make these changes, and sign the SLA, we'll merge! 

Thanks again for the work here!

**Comment by CaptureTheBox** [comment]
Ping @mabdi - Once you make the requested changes and sign the SLA, we can merge! Thanks again for your awesome work here.

**Comment by juliannagler** [comment]
Ping @mabdi  - Once you make the requested changes and sign the SLA, we can merge! Thanks again for your awesome work here.

**Comment by mabdi** [comment]
@juliannagler: thanks for suggested changes.  
@javuto, @juliannagler: SLA is signed.
I'm sorry for the delay.

**Comment by juliannagler** [comment]
Great, thanks so much for your contribution @mabdi! Merging!

**Pull request merged**
