### PR TITLE
fix https://github.com/facebook/fbctf/issues/209

### PR DESCRIPTION
**Pull request by qazbnm456**
fix https://github.com/facebook/fbctf/issues/209

### CODE REVIEW

**Comment by javuto** [comment]
Awesome! Great work @qazbnm456

**Comment by gsingh93** [comment]
Thanks for the fix. Does the hhvm process run as root at the moment? We might want to consider running it as www-data for better security, and so we don't have to chmod in the future. In any case, this is fine for now.

**Comment by qazbnm456** [comment]
It runs as www-data, but socket is owned by root. Therefore, I have to `chown` socket to www-data to make it writable by nginx. 

I found this issue has been reported here (https://github.com/facebook/hhvm/issues/6336).

**Comment by aarondanielson** [comment]
@gsingh93 Can we take another look at this?  @qazbnm456 has found the solution, perhaps adding a command-line argument to specify the socket owner is a good way to deal with this issue.

**Pull request merged**
