### PR TITLE
Added Hindi Translation

### PR DESCRIPTION
**Pull request by Akhil09**

### CODE REVIEW

**Comment by juliannagler** [comment]
Hey @Akhil09, thanks so much for the work here! 

We've had a local speaker validate the translations. His suggested changes are attached here. Once you make the requested changes, we'll merge! 

Thanks again! 

[Requested Hindi Changes](https://github.com/facebook/fbctf/files/577177/Copy.of.2FBCTF_Changes_Tracker_Hindi.xlsx)

[Full string dump w/ suggested changes included](https://github.com/facebook/fbctf/files/577178/Hindi.FBCTF.Translation.1.docx)

**Comment by javuto** [comment]
Ping @Akhil09

**Comment by Akhil09** [comment]
Hey! Right now..my exams are going on so I will try to do it as soon as i can.

Regards.

**Comment by CaptureTheBox** [comment]
Not a problem, thanks @Akhil09! Good luck with the exams :)

**Comment by juliannagler** [comment]
No problem @Akhil09! Good luck with the exams :)

**Comment by juliannagler** [comment]
Ping @Akhil09

**Comment by juliannagler** [comment]
Ping @Akhil09 

If you can't get to the suggested edits this week, we can create a new PR with the final changes. Want you to get the credit for the work you did though!

**Pull request closed without merging**
